JuliaSmoothOptimizers/SolverBenchmark.jl

REQUIRE
docs/src/api.md
examples/pkgbmark.jl
src/SolverBenchmark.jl
src/pkgbmark.jl
src/profiles.jl
test/bmark_suite.jl
test/pkgbmark.jl
test/runtests.jl

This PR adds a function to profile solvers 2x2 and facilities to profile packages based on PkgBenchmark benchmarks.

multiple profiles + PkgBenchmark profiles

---

docs/src/api.md
src/pkgbmark.jl
test/pkgbmark.jl

Profile master vs a commit or a pull request (checked out locally) in a given package. Example:
```julia
julia> using PkgBenchmark
julia> commit = benchmarkpkg("Krylov")  # current state of repository
julia> master = benchmarkpkg("Krylov", "master")
julia> judgement = judge(commit, master)
julia> using SolverBenchmark
julia> p = profile_package(judgement)
```
Result:

profile judgement results

---

src/profiles.jl

- Add width and height in `profile_solvers`;
- Remove excessive xlabel and ylabel in `profile_solvers`;
- Change `import Plots` to `using Plots` so `Plots.foo` changes to `foo`.

profile_solvers improvements

---

test/pkgbmark.jl

The problem is that it erases the current changes, so testing before commit means you lose your work.

Only change branches during pkgmark tests on CI

---

src/profiles.jl

This makes it possible to, e.g., set a title or the legend position easily.

pass extra args through performance_profile

---

Project.toml
src/formatting.jl
src/join.jl
src/pkgbmark.jl
test/pkgbmark.jl
test/tables.jl

This should also get rid of the annoying warnings in the documentation.

update DataFrame syntax to resolve warnings

---

examples/pkgbmark.jl
src/profiles.jl

@amontoison 
Example: https://gist.github.com/dpo/a2e6a0ae884219057e1c9b139fc8f46a

Fix colors

---

src/pkgbmark.jl
test/pkgbmark.jl

So it seems there was an error after all.

fix pkgbmark test

---

src/formats.jl
src/latex_formats.jl
test/output_results.jl
test/tables.jl

Handle missing

---

Project.toml
src/SolverBenchmark.jl
test/test_bmark.jl

Following SolverTools bump to 0.5.0.

add SolverCore

---

.github/workflows/Documentation.yml
.github/workflows/ci.yml
README.md
src/pkgbmark.jl
test/pkgbmark.jl

These changes were made automatically, please check before merging.

[AUTO] Change master to main

---

docs/src/tutorial.md

I think it is better to put it after the plots to separate it from the original example

updated to show the graphs first

---

Project.toml

Benefit from the last update in BenchmarkProfiles.jl

Version 0.5.1

---

docs/src/tutorial.md
src/latex_formats.jl

Requires https://github.com/JuliaSmoothOptimizers/BenchmarkProfiles.jl/pull/84 and some resolution to #121.

fixes to documentation

---

src/run_solver.jl

Fix https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/issues/123

Fix bug counters

---

docs/Project.toml
docs/make.jl

Investigating whether this is the reason why the doc build is failing #142

Bump DataFrames in doc

---

.github/workflows/Documentation.yml

Bump to TinyText 2024 in doc

---

.breakage/Project.toml
.breakage/get_jso_users.jl
.github/workflows/Breakage.yml
copier-answers.jso.yml

Automated update using JSOBestieTemplate

Update with JSOBestieTemplate for SolverBenchmark

---

src/run_solver.jl
test/test_bmark.jl

Bmark_solvers with solver_specific stats bug

---

src/profiles.jl

A microscopic code improvement

profile_solvers: micro improvement
